version: '3'

services:
  go-file-gate-app:
    build:
      context: ./go-file-gate
      dockerfile: Dockerfile
    command: ["/wait-for-it.sh", "db:5432","--", "/wait-for-it.sh", "redis:6379","--","/wait-for-it.sh", "rabbitmq:5672", "--", "/go-file-gate-app"]
    image: go-file-gate-app:latest
    ports:
      - "8080:8080"
    environment:
      LINE_CHANNEL_ID: ${LINE_CHANNEL_ID}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: 1234
      APP_ENV: dev
    depends_on:
      - redis
      - db
      - rabbitmq
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poker_join_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Change to your desired email
      PGADMIN_DEFAULT_PASSWORD: password  # Change to your desired password
    ports:
      - "5433:80"  # You can access pgAdmin at http://localhost:5433
    depends_on:
      - db
  
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  file-flow-ui-app:
    build: 
      context: ./file-flow-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - go-file-gate-app
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata:
  rabbitmq-data: