app:
  name: 'GoChatApp'
  version: '1.0.0'
  domain_url: https://57a9-2001-b011-380f-1fed-2d4e-c700-1f83-e40.ngrok-free.app

http:
  port: '8080'

postgres:
  pool_max: 10

log:
  log_level: 'debug'

redis:
  host: 'localhost'
  port: '6379'
  password: ''

rabbit_mq:
  host: 'localhost'
  port: '5672'
  username: 'guest'
  password: 'guest'
