app:
  name: 'GoChatApp'
  version: '1.0.0'
  domain_url: https://69fb-2001-b011-380f-192b-c8e4-df40-3a48-c977.ngrok-free.app

http:
  port: '8080'

postgres:
  pool_max: 10

log:
  log_level: 'debug'

redis:
  host: 'localhost'
  port: '6379'
  password: ''

rabbit_mq:
  host: 'localhost'
  port: '5672'
  username: 'guest'
  password: 'guest'

mailhog:
  host: 'localhost'
  port: '1025'
